language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master

env:
  global:
    - secure: "TmPBOkNcOPGwQuXpXv6fP45vras6bquRApblyCTsxfLlKD0q58a5hxjPlt3De51FE/3Kqb0y0le8NgZ/BPGCBTQo9YlIVORZJYPvYAgXJ+xd1OyowJdTycpu9FZlO9brzw9Yn4SJDIwlRtBOiCI3F81RvqpBKcT8lz/uNXTxAl4="
    - secure: "Uimw3QuOoJEcsxQNK7/XwUcBgaWV5z6QyfDJUmnEUwSP4qrmpWbQgEAP2p60Z5fKrUVrbdG43eZsoh3qfBvQDwsMojfsCKawSMmCo5A3c9JRL63VOG7cFGCFZ9FUPSe0frd/bzGeH+eNazpplytWHKanN0xOtqmfIKeyTx2c+wA="

after_success:
  - mvn clean deploy --settings settings.xml
